# Generated by Django 3.1.3 on 2020-11-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_id', models.CharField(max_length=20)),
                ('cash', models.CharField(max_length=20)),
                ('amount', models.CharField(max_length=20)),
                ('date', models.DateField()),
            ],
        ),
    ]
