# Generated by Django 3.1.3 on 2020-11-30 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='orphanid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orphanage.orphan'),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='parentid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orphanage.parent'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donorid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orphanage.donor'),
        ),
    ]
