# Generated by Django 3.1.3 on 2020-12-07 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0002_auto_20201205_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoption',
            name='adopted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orphan',
            name='adopted',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='orphan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orphanage.orphan'),
        ),
    ]
