# Generated by Django 3.1.3 on 2020-11-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0002_auto_20201130_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoption',
            name='orphanid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='adoption',
            name='parentid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donorid',
            field=models.IntegerField(),
        ),
    ]
