# Generated by Django 3.1.3 on 2020-12-01 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0002_auto_20201201_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orphan',
            name='age',
        ),
    ]
