# Generated by Django 3.1.3 on 2020-12-22 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0003_staff_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='deleted',
        ),
    ]
