# Generated by Django 3.1.3 on 2020-12-07 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0003_auto_20201207_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoption',
            name='adopted',
        ),
    ]
