# Generated by Django 3.1.3 on 2020-12-04 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0003_remove_orphan_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoption',
            name='orphanname',
        ),
    ]
