# Generated by Django 3.1.3 on 2020-12-04 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0004_remove_adoption_orphanname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='pincode',
        ),
    ]
