# Generated by Django 3.1.3 on 2020-12-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0005_pdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='address',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='city',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='country',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='state',
        ),
        migrations.AddField(
            model_name='parent',
            name='pincode',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pdetails',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
