# Generated by Django 3.1.3 on 2020-12-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0006_auto_20201216_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='ddetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.IntegerField(default=0)),
                ('h_no', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='donation',
            old_name='amount',
            new_name='kind',
        ),
        migrations.AlterField(
            model_name='donation',
            name='cash',
            field=models.IntegerField(max_length=20),
        ),
    ]
