# Generated by Django 3.1.3 on 2020-12-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0007_auto_20201217_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='cash',
            field=models.IntegerField(),
        ),
    ]
