# Generated by Django 3.1.3 on 2020-12-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0008_auto_20201217_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='donor_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='donor_phno',
            new_name='phno',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='firstname',
            new_name='parentname',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='lastname',
        ),
        migrations.AddField(
            model_name='donor',
            name='pincode',
            field=models.IntegerField(default=0),
        ),
    ]
