# Generated by Django 3.1.3 on 2020-12-17 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orphanage', '0009_auto_20201217_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='city',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='country',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='state',
        ),
    ]
